<div class="templateForm">
    <div class="main-container">
        <section>
            <h1>Mi formulario</h1>
            <p class="descripcion">Formulario de datos personales para ser enviados a un nuevo template</p>
        </section>

        <section>
            <div class="offert"><span>Estos son mis</span> datos peronales</div>
            <div class="form-container">
                <form action="#">

                    <input id="firstNameInput" type="text" placeholder="First Name">
                    <div id="firtNameError" class="error-container">
                        <!--<img class="icon-error" src="<?/*= $this->getViewFileUrl('images/icon-error.svg') */?>"></img>
                        <p class="error">First Name cannot be empty</p>-->
                    </div>

                    <input id="lastNameInput" type="text" placeholder="last Name">
                    <div id="lastNameError" class="error-container"></div>

                    <input id="emailInput" type="email" placeholder="email addres">
                    <div id="emailError" class="error-container"></div>

                    <input id="passInput" type="password" placeholder="password">
                    <div id="passError" class="error-container"></div>

                    <input id="button" type="submit" value="Enviar datos">
                </form>
                <p class="terms">Challenge by Juan David Campo Chara <a href="#">juandacampo@gmail.com</a></p>
            </div>
        </section>
    </div>
</div>
